apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-hpc-app-pipeline
spec:
  params:
    - name: repository
      description: The Git Repository for the Application Source Code. If empty, the Repository url will be found from toolchain
    - name: branch
      description: The Branch for the Application Source Code
      default: "master"
    - name: revision
      description: The Revision for the Application Source Code
      default: ""
    - name: git-token
      description: access token for the git repo
    - name: region
      description: The IBM Cloud Region in which Virtual Server Instance is running
    - name: api
      description: The IBM Cloud API Endpoint
    - name: apikey
      description: The IBM Cloud API Key
    - name: fail-on-scanned-issues
      description: Force failure of task when vulnerability advisor scan issues are found
      default: "true"
    - name: app-name
      description: The name of the application passed as environment variable
    - name: pipeline-debug
      default: "0"
    - name: pr-url
      description: The Pull Request URL
    - name: commit-timestamp
      description: The Commit Timestamp as set by the Trigger Binding based on the Event Listener invoked
    - name: scm-type
      description: The Source Code Management Type as set by the Trigger Binding based on the Event Listener invoked
    - name: virtual-server-instance
      description: The IP Address of the Virtual Server Instance
    - name: host-ssh-keys
      description: The private SSH Key required to login to the Virtual Server Instance
    - name: host-user-name
      description: The username required to login to the Virtual Server Instance
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: git-clone-application-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "apikey"
        - name: git-access-token
          value: $(params.git-token)
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
        - name: revision
          value: $(params.revision)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: git-credentials-json-file
          value: credentials.json          
      workspaces:
        - name: output
          workspace: pipeline-ws 
    - name: build-source
      runAfter:
        - git-clone-repo
      taskRef:
        name: gcc-build
      params:
        - name: command
          value: gcc -o $(params.app-name) app.c
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: unit-tests
      taskRef:
        name: gcc-build
      runAfter: 
        - build-source
      params: 
        - name: command
          value: "./$(params.app-name) 11"
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
    - name: upload-artifacts
      runAfter: 
        - unit-tests
      taskRef:
        name: upload-artifacts
      params:
        - name: virtual-server-instance
          value: $(params.virtual-server-instance)
        - name: host-ssh-keys
          value: $(params.host-ssh-keys)
        - name: host-user-name
          value: $(params.host-user-name)
      workspaces:
        - name: output
          workspace: pipeline-ws

