apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gcc-build
spec:
  params:
    - name: repository
      description: The Git Repository for the Application Source Code
      default: repository
    - name: command
      description: command to exec
  workspaces:
    - name: output
      description: A workspace to store the output of intermittent steps
      mountPath: /usr/src/myapp
  steps:
    - name: gcc-build
      image: gcc
      workingDir: /usr/src/myapp
      script: |          
          #!/bin/bash
          set -e ;
          ls -la
          echo "$(params.command)"
          $(params.command)
---          
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: upload-artifacts
spec:
  params:
      - name: virtual-server-instance
      - name: host-ssh-keys
      - name: host-user-name
  workspaces:
    - name: output
      description: A workspace to store the output of intermittent steps
      mountPath: /artifacts
  steps:
    - name: upload-artifacts
      image: ubuntu
      workingDir: /artifacts
      script: |          
          #!/bin/bash
          set -e ;
          echo "uploading"
          ls -la



